theme: jekyll-theme-minimal
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
name: 
title: 
github:
  is_project_page: false
