theme: jekyll-theme-cayman
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
name: Privacy Policy
title: null
github:
  is_project_page: false
